-- AlterTable
ALTER TABLE "like" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "views" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP;
