import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ReactQuearyProvider } from "@/utils/quaryprovider";
import { Toaster } from 'sonner'
import SideBar from "@/components/sideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQuearyProvider>
        <Toaster richColors></Toaster>
        <Navbar></Navbar>
        <SideBar></SideBar>
        {children}
        </ReactQuearyProvider>
        </body>
    </html>
  );
}
